# Generated by Django 3.0.5 on 2020-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item_title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('service_item_text_title', models.CharField(max_length=150, verbose_name='Описание на главной странице')),
                ('service_item_text', models.TextField(verbose_name='Полное описание услуги')),
                ('service_item_price', models.CharField(max_length=50, verbose_name='Стоимость услуги')),
                ('service_item_additional_info', models.CharField(max_length=150, verbose_name='Дополнительная информация')),
            ],
        ),
    ]
