# Generated by Django 3.0.5 on 2020-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_item_additional_info',
            field=models.TextField(max_length=150, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_item_text',
            field=models.TextField(max_length=500, verbose_name='Полное описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_item_text_title',
            field=models.TextField(max_length=150, verbose_name='Описание на главной странице'),
        ),
    ]
