# Generated by Django 3.0.5 on 2020-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteServices', '0005_auto_20200529_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteservice',
            name='service_item_price',
            field=models.CharField(default='Отсутствует', max_length=50, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='siteservice',
            name='service_item_text',
            field=models.TextField(default='Отсутствует', max_length=1000, verbose_name='Полное описание услуги'),
        ),
    ]
