# Generated by Django 3.0.5 on 2020-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_review', models.CharField(max_length=45, verbose_name='Имя')),
                ('email_review', models.CharField(max_length=45, verbose_name='Почта')),
                ('body_review', models.TextField(max_length=400, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
