# Generated by Django 3.0.5 on 2020-05-30 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siteReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetreview',
            name='time_pub_review',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва'),
        ),
    ]
