# Generated by Django 3.0.5 on 2020-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(choices=[('dsd', '32323'), ('dsd', '32323'), ('dsd', '32323')], max_length=100)),
            ],
        ),
    ]
