# Generated by Django 3.0.5 on 2020-05-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item_title_home_page', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('service_item_text_title_home_page', models.TextField(max_length=150, verbose_name='Описание на главной странице')),
                ('service_item_url_home_page', models.URLField(max_length=100, verbose_name='Ссылка на услугу')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.DeleteModel(
            name='HomePageServices',
        ),
    ]
