# Generated by Django 3.0.5 on 2020-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteHomePage', '0003_delete_homepageservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_item_title_home_page', models.CharField(max_length=50, verbose_name='Название')),
                ('advantage_item_text_home_page', models.TextField(max_length=150, verbose_name='Краткое описание')),
                ('advantage_item_icon', models.CharField(choices=[('fas user-tie fa-10x', 'Человек и галстук '), ('fas dollar-sign fa-10x', 'Знак доллар')], default='fas user-tie fa-10x', max_length=25)),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
