# Generated by Django 3.0.5 on 2020-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHomePage', '0004_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='advantage_item_icon',
            field=models.CharField(choices=[('fas user-tie fa-10x', 'Человек и галстук '), ('fas dollar-sign fa-10x', 'Знак доллар')], default='fas user-tie fa-10x', max_length=25, verbose_name='Список иконок'),
        ),
    ]
