# Generated by Django 3.0.5 on 2020-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHomePage', '0005_auto_20200530_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('body', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='advantage',
            name='advantage_item_icon',
            field=models.CharField(choices=[('fas fa-user-tie fa-10x', 'Человек и галстук '), ('fas fa-dollar-sign fa-10x', 'Доллар'), ('fas fa-percent fa-10x', 'Процент'), ('fas fa-money-check-alt fa-10x', 'Кредитная карта')], default='fas fa-user-tie fa-10x', max_length=30, verbose_name='Список иконок'),
        ),
    ]
