# Generated by Django 3.0.5 on 2020-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHomePage', '0006_auto_20200530_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='phone',
            field=models.TextField(),
        ),
    ]
