# Generated by Django 3.0.5 on 2020-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteHomePage', '0007_auto_20200530_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(max_length=250, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='phone',
            field=models.CharField(max_length=45, verbose_name='Телефон'),
        ),
    ]
